trigger:  none
pool : 'LK_agent'

steps:

- task: SonarScanner@1
  inputs:
    endpoint: 'LocalSonarQube'
    sonarServer: 'LocalSonarQube'
    version: '4.8.0.2856'
    configMode: 'manual'
    projectKey: 'Sonar'
    projectName: 'Sonar'
    projectVersion: '1.0'
    sources: 'F:\Devops_insider\azure-devsecops-batch-17\CodeSamples\TodoApp\FrontendTodo\ReactTodoUIMonolith'
    extraProperties: |
      # Write your additional sonar-scanner properties here.
      
      sonar.exclusions=**\tests
